(TeX-add-style-hook "ldDesign"
 (lambda ()
    (LaTeX-add-bibliographies)
    (LaTeX-add-labels
     "eq:rsquared"
     "tbl:ccpowerattr"
     "sec:genomescans"
     "tbl:scenario1"
     "sec:bayesianfunctions"
     "eq:abf")
    (TeX-add-symbols
     "ccDesign"
     "BayesQTLBIC"
     "Pr"
     "case"
     "control"
     "data"
     "bb"
     "Bb"
     "BB"
     "ie"
     "eg"
     "etal"
     "cf")
    (TeX-run-style-hooks
     "natbib"
     "authoryear"
     "round"
     "Sweave"
     "amsmath"
     "url"
     "sidecap"
     "graphicx"
     "fontenc"
     "T1"
     "inputenc"
     "utf8x"
     "ucs"
     "latex2e"
     "amsart10"
     "amsart"
     "a4paper"
     "10pt")))

